"""DNS threat hunting: tunneling, NXDOMAIN anomalies, TXT abuse.

Every signal here is *combined* — a single "long label" or one odd TXT
record fires nothing. Confidence grows with the number of independent
signals observed for the same domain, and the finding lists exactly
which signals fired.
"""

from __future__ import annotations

from netsleuth.analyzers.dns import shannon_entropy
from netsleuth.enrichment.mitre import mitre
from netsleuth.extraction.encodings import looks_like_base32, looks_like_hex
from netsleuth.models import Confidence, Finding, Severity

LONG_LABEL = 32                  # tunnel chunk size territory
HIGH_ENTROPY = 3.6               # bits/char for a random-looking label
MANY_SUBDOMAINS = 25             # unique subdomains per base domain
TXT_BULK = 4                     # TXT answers for one domain in one capture
NXDOMAIN_BULK = 15
LONG_NAME = 100

# Left-hand labels that identify *Windows AD service discovery and proxy
# auto-detection*, not data smuggling. SRV lookups always carry a leading
# underscore label (_ldap, _kerberos, _kadmin, _gc, _sites, _msdcs…);
# WPAD/ISATAP probe a fixed well-known name; nbt-* is NetBIOS. Their
# labels can be long and GUID-like (site names), which mimics tunneling
# entropy unless they are filtered out first.
_WELL_KNOWN_PREFIXES = ("wpad", "isatap", "nbt-")


def well_known_query(name: str) -> bool:
    """True for names generated by standard Windows/domain behavior."""
    if not name:
        return False
    labels = name.rstrip(".").split(".")
    if any(l.startswith("_") for l in labels[:-1]):
        return True                     # SRV-style service record lookup
    first = labels[0].lower()
    return any(first == p or first.startswith(p + ".") or first.startswith(p + "-")
               for p in _WELL_KNOWN_PREFIXES)


def _active_queries(result, domain: str):
    """Records for *domain* (queries and their responses), minus
    well-known-pattern names. NXDOMAIN codes ride on response records,
    so both directions must be kept."""
    return [q for q in result.dns.queries
            if result.dns.base_domain(q.name) == domain
            and q.name
            and not well_known_query(q.name)]


def _restats(result, domain: str):
    """Recompute the tunneling signals over the filtered query set.

    Mirrors the analyzer's math (label length, per-label entropy for
    labels ≥ 8 chars, unique subdomain prefixes, TXT answers) so a
    domain whose only "suspicious" labels come from _ldap/wpad-style
    names scores clean, while genuinely random subdomains still fire.
    """
    records = _active_queries(result, domain)
    if not records:
        return None
    longest = 0
    max_ent = 0.0
    subs = set()
    txt = 0
    names = set()
    for q in records:
        names.add(q.name)
        labels = q.name.rstrip(".").split(".")
        for label in labels:
            longest = max(longest, len(label))
            if len(label) >= 8:
                max_ent = max(max_ent, shannon_entropy(label))
        subs.add(".".join(labels[:-1]) or "(root)")
        if q.answer_type == "TXT" or q.qtype == "TXT":
            txt += len(q.answers)
    return {"queries": len(names), "longest_label": longest,
            "max_entropy": max_ent, "subdomains": subs, "txt": txt}


def _example_queries(result, domain: str, n: int = 3) -> list[str]:
    seen = []
    for q in result.dns.queries:
        if result.dns.base_domain(q.name) == domain and q.name not in seen:
            seen.append(q.name)
        if len(seen) >= n:
            break
    return seen


def detect_dns_tunneling(result) -> list[Finding]:
    if result.dns is None:
        return []
    findings = []
    for st in result.dns.domain_stats.values():
        if st.queries == 0:
            continue
        # re-evaluate over queries that are NOT well-known service
        # discovery; a domain whose suspicious-looking labels all come
        # from _ldap/wpad-style names is not a tunnel
        restats = _restats(result, st.domain)
        if restats is None:
            continue                    # every query was well-known-pattern
        signals: list[str] = []
        examples = _example_queries(result, st.domain)

        if restats["longest_label"] >= LONG_LABEL:
            signals.append(f"unusually long labels (max {restats['longest_label']} chars; "
                           "normal hostnames rarely exceed ~25)")
        if restats["max_entropy"] >= HIGH_ENTROPY:
            signals.append(f"high-entropy labels (max {restats['max_entropy']:.3f} bits/char "
                           "— consistent with encoded data, not words)")
        if len(restats["subdomains"]) >= MANY_SUBDOMAINS:
            signals.append(f"{len(restats['subdomains'])} unique subdomains queried "
                           "(rapidly-changing left-hand parts)")
        if restats["txt"] >= TXT_BULK:
            signals.append(f"{restats['txt']} TXT responses (TXT is the classic "
                           "channel for tunnel replies)")
        if not signals:
            continue

        encoded_look = any(looks_like_base32(l.split(".")[0])
                           or looks_like_hex(l.split(".")[0])
                           for l in examples if l)
        if encoded_look:
            signals.append("left-most labels look Base32/Hex-encoded")

        if len(signals) >= 3:
            severity, conf = Severity.HIGH, Confidence.HIGH
        elif len(signals) == 2:
            severity, conf = Severity.MEDIUM, Confidence.MEDIUM
        else:
            severity, conf = Severity.LOW, Confidence.LOW

        findings.append(Finding(
            id=f"dns.tunnel.{st.domain}",
            title=f"Possible DNS tunneling via {st.domain}",
            severity=severity,
            confidence=conf,
            description=(f"{st.queries} queries to *.{st.domain} show "
                         + "; ".join(signs.lower() for signs in signals) + "."),
            explanation=(
                "DNS tunneling encodes data (C2 commands or exfiltrated bytes) "
                "into hostname labels — e.g. "
                "NBSWY3DPFQQFO33SNRSC65LJMQ.tunnel.example.com. The encoding "
                "forces long, high-entropy, ever-changing subdomains, which is "
                "what these signals measure. Legitimate services (CDNs, "
                "load balancers) can also generate many subdomains — check "
                "whether the labels decode to something meaningful before "
                "calling it malicious."),
            verification=(f'In Wireshark: dns.qry.name contains "{st.domain}" '
                          "— inspect the queried names; try Base32/Base64-"
                          "decoding the left-most label of the longest ones."),
            evidence=[f"signals fired: {len(signals)}"] +
                     [f"example query: {e[:100]}" for e in examples],
            hosts=sorted({q.client for q in result.dns.queries
                          if result.dns.base_domain(q.name) == st.domain}),
            protocol="dns",
            first_ts=min((q.ts for q in result.dns.queries
                          if result.dns.base_domain(q.name) == st.domain), default=None),
            wireshark_filters=[f'dns.qry.name contains "{st.domain}"'],
            mitre=[mitre("T1071.004", "DNS used as a data channel"),
                   mitre("T1132.001", "hostname labels consistent with encoded data")],
        ))
    return findings[:8]


def detect_nxdomain_anomaly(result) -> list[Finding]:
    if result.dns is None:
        return []
    findings = []
    for st in result.dns.domain_stats.values():
        if st.queries == 0:
            continue
        min_nx = 8 if (st.nxdomain / st.queries >= 0.75) else NXDOMAIN_BULK
        if st.nxdomain < min_nx:
            continue
        if st.nxdomain / st.queries < 0.5:
            continue
        # WPAD and DC-locator probes NXDOMAIN on every retry by design;
        # count failures only over queries that are not well-known ones
        active = _active_queries(result, st.domain)
        if not active:
            continue
        nx = sum(1 for q in active if q.response_code == "NXDOMAIN")
        min_active_nx = 8 if (nx / len(active) >= 0.75) else NXDOMAIN_BULK
        if nx < min_active_nx or nx / len(active) < 0.5:
            continue
        st_nx, st_q = nx, len(active)
        findings.append(Finding(
            id=f"dns.nx.{st.domain}",
            title=f"High NXDOMAIN rate for {st.domain} "
                  f"({st_nx}/{st_q})",
            severity=Severity.LOW,
            confidence=Confidence.LOW,
            description=(f"{st_nx} of {st_q} non-service queries under "
                         f"{st.domain} returned NXDOMAIN (domain does not exist)."),
            explanation=(
                "Bursts of NXDOMAIN usually mean one of: a DGA (malware "
                "generating random domains to find its C2), subdomain "
                "brute-forcing, or simply broken software retrying a "
                "hard-coded name. On its own this is weak — correlate with "
                "the querying host's other activity."),
            verification=f'In Wireshark: dns.qry.name contains "{st.domain}" '
                         "&& dns.flags.rcode == 3",
            evidence=[f"NXDOMAIN: {st_nx}/{st_q} non-service queries"],
            hosts=sorted({q.client for q in result.dns.queries
                          if result.dns.base_domain(q.name) == st.domain}),
            protocol="dns",
            wireshark_filters=[f'dns.qry.name contains "{st.domain}" '
                               "&& dns.flags.rcode == 3"],
            mitre=[mitre("T1071.004", "high-volume failing DNS lookups "
                                      "(DGA-style behavior)")],
        ))
    return findings[:4]


def detect_suspicious_txt(result) -> list[Finding]:
    if result.dns is None:
        return []
    interesting: list[tuple[str, str]] = []
    for st in result.dns.domain_stats.values():
        for val in st.txt_values:
            if len(val) >= 60 and (looks_like_base32(val.upper()) or
                                   shannon_entropy(val) >= 4.2):
                interesting.append((st.domain, val))
    if not interesting:
        return []
    domain, val = interesting[0]
    return [Finding(
        id=f"dns.txt.{domain}",
        title=f"Dense data in DNS TXT record for {domain}",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description=(f"TXT record carries {len(val)} characters of "
                     "high-entropy, encoded-looking data."),
        explanation=(
            "TXT records legitimately hold SPF/DKIM data, but those are "
            "readable strings like \"v=spf1 -all\". Long opaque blobs are "
            "how DNS-tunnel C2 replies and some malware configs travel. "
            "Try Base32/Base64-decoding the value."),
        verification=f'In Wireshark: dns.qry.name == "{domain}" && dns.txt',
        evidence=[f"TXT value ({len(val)} chars): {val[:80]}…",
                  f"entropy: {shannon_entropy(val):.1f} bits/char"],
        hosts=sorted({q.client for q in result.dns.queries
                      if result.dns.base_domain(q.name) == domain}),
        protocol="dns",
        wireshark_filters=[f'dns.qry.name == "{domain}" && dns.txt'],
        mitre=[mitre("T1071.004", "data-bearing TXT records")],
    )]
